### PR TITLE
Refine interface

### PR DESCRIPTION
**Pull request by roneyrao**
1. Expose CacheableRequest instance itself instead of return a request function.
2. Expose CachePolicy and allow being passed in.

### CODE REVIEW

**Comment by lukechilds** [comment]
What is your use case for passing in your own CachePolicy class?

**Comment by roneyrao** [comment]
I want to cache files always, so method `storable` of `CachePolicy` is patched to always return true. Please refer to my project https://github.com/roneyrao/download-webpack-plugin

**Comment by lukechilds** [comment]
Hmmn, that's not the intended use case of this module, it's for implementing RFC 7234 compliant cache transparently.

It doesn't make sense to add new constructor arguments to inject something that should be a constant, just to enable a single use case.

If you just want to permanently cache files, I'd recommend you just use Keyv directly with `http.request` or a nice request library like Got. Then you can save the responses straight into Keyv and pull them straight out of Keyv.

There's a lot of added complexity in this module that you're short circuiting by just force caching everything. Also, I don't think patching `CachePolicy` so `storable` is always true will do what you think it does. Just because something stored in the cache, doesn't mean it'll be retrieved if it's no longer valid.

**Comment by roneyrao** [comment]
Thank you for your instruction, I will rethink of it.

**Pull request closed without merging**
