### PR TITLE
fix: request args treatment should be consistent with http.request

### PR DESCRIPTION
**Pull request by jstewmon**
- adds support for URL instances being passed to request
- when request argument is an object, normalize it according to
  the options accepted by http.request instead of url.format

fixes:
- https://github.com/sindresorhus/got/pull/519
- https://github.com/sindresorhus/got/pull/487

cc @sindresorhus

### CODE REVIEW

**Comment by jstewmon** [comment]
I only added one new test for when the argument is a URL instance. I would have like to add tests asserting the cache keys, but wasn't sure where to put them. Open to suggestions.

**Comment by lukechilds** [comment]
Or maybe update this test to more thoroughly check different queries:

https://github.com/jstewmon/cacheable-request/blob/57488296a7501f4f005888600ab6c222a89a4e4c/test/cache.js#L128-L139

**Comment by jstewmon** [comment]
I added a bunch of tests around the cache key format based on the argument types supported by http.request.

I changed the configuration used with normalize-url, so that `www` subdomains and trailing slashes are significant. I realize it's opinionated, but I think those settings align with the principle of least surprise. I've never leveraged this module myself, but I would suggest that the parameters used to normalize the key should be configurable by the user.

**Comment by lukechilds** [comment]
This looks great, thanks!

**Comment by lukechilds** [comment]
@sindresorhus @jstewmon Thanks guys! Just published `cacheable-request@4.0.0` 🎉

**Pull request merged**
