### PR TITLE
Code refactor to make it modular

### PR DESCRIPTION
**Pull request by adityapatadia**
Part of #71 fixes.

### CODE REVIEW

**Comment by lukechilds** [comment]
Can you do a single atomic change per PR.

So for example, this PR could be:

>Extract URL and option parsing logic into separate function

and would only contain this commit: https://github.com/lukechilds/cacheable-request/pull/81/commits/5f632decac7134fd3bd090177df3d6530fb60f71

**Comment by adityapatadia** [comment]
Okay I did exactly that but then I committed to forked repo and it keeps adding commits to this PR. Can you check and approve individual commits this one time? I will take care next time while opening PR.

**Comment by lukechilds** [comment]
You can still commit to a forked repo, you need to create a new branch per feature.

I see you're doing all your work in master which is why you're having the issue.

You can fix that by forking master into a new branch called `options-parsing`, then remove all the extra commits, then re-submit this PR from that branch. You would do that like this:

```shell
# fork master into options-parsing
git checkout -b options-parsing

# Remove new commits (where n is number of commits)
git reset HEAD~n --hard

# Push
git push --set-upstream origin options-parsing
```

Now open a PR from your `options-parsing` branch.

If you want to submit another PR, create a new branch from master, work in there and then submit another pull request from that branch.

e.g:

```shell
# checkout master so you don't fork from options-parsing
git checkout master

# fork master into options-parsing
git checkout -b node-v12

# Do some work and add some commits

# Push
git push --set-upstream origin node-v12
```

and then open a PR from that branch.

Now you have two local branches, `options-parsing` and `node-v12` that relate to two different pull requests. You can work on them both and push new changes without affecting the other pull request.

**Comment by adityapatadia** [comment]
Okay.

**Comment by adityapatadia** [comment]
Please check this now. All tests are passing. I would still insist to merge it after reviewing each commit. I really don't want to deal with merge conflicts by creating 5 branches.

**Comment by lukechilds** [comment]
I'm happy for you to remove the async IIFEs in favour of Promises, I agree it's more readable. However the way you've done it is not functionally equivalent, it breaks the current behaviour.

Currently the response event is emitted instantly, writing/deleting cache entries. Your change awaits all these changes before returning a response.

See this PR (https://github.com/lukechilds/cacheable-request/pull/41) which introduced async/await for how the Promise equivalents should look.

>I would still insist to merge it after reviewing each commit. I really don't want to deal with merge conflicts by creating 5 branches.

It's ok to group code refactor changes together, although the smaller the PR the better as it makes it much easier to review. I was referring to the Node.js v12 stuff, which isn't really relative in the context of this PR.

**Comment by adityapatadia** [comment]
I understood that behaviour is changed but isn't it a good change?
For example, before this change,

```javascript
await got("https://www.google.com");
await got("https://www.google.com");
```

Above second request might not use cache as the response event is fired first and cache is written later. In the PR that I raised, the cache writing will be ensured and second request will always be able to use cache. I faced that same issue in high traffic scenario and hence the change. It's also not breaking any APIs but just makes this module more reliable in high request scenario.

**Comment by adityapatadia** [comment]
I can obviously change the behaviour to previous one by moving the ee.emit code inside the if/else block but I highly recommend that we wait for cache writing first before emitting anything.

**Comment by adityapatadia** [comment]
There are obviously other questions in my mind like whether the response event should be emitted at all if the error is raised? In current case, response and error both are emitted but ideally, for a given request only one of them should be emitted. User is using this module to cache the request so if caching is not done for a response, no point emitting the response event.

This obviously would break API so it should be discussed separately.

**Comment by adityapatadia** [comment]
Please let me know what you think.

**Comment by adityapatadia** [comment]
@lukechilds Please let me know your thoughts. I would like to proceed to make more changes once this is merged.

**Comment by adityapatadia** [comment]
Resolved all conflicts.

**Comment by adityapatadia** [comment]
> I understood that behaviour is changed but isn't it a good change?
> For example, before this change,
> 
> ```js
> await got("https://www.google.com");
> await got("https://www.google.com");
> ```
> 
> Above second request might not use cache as the response event is fired first and cache is written later. In the PR that I raised, the cache writing will be ensured and second request will always be able to use cache. I faced that same issue in high traffic scenario and hence the change. It's also not breaking any APIs but just makes this module more reliable in high request scenario.

@lukechilds please let me know your thoughts on this. Once you approve this change, I can create separate PRs.

**Comment by lukechilds** [comment]
I don't think that's a good change.

It's reducing the performance (waiting for a DB write after each request) and isn't really offering any benefit.

If the second request doesn't use the cache in certain scenarios where identical requests are happening close together, that's ok, it won't make a large impact on performance.

The important thing is that we return the response to the user as fast as possible. Extra work like deleting stale cache entries or writing responses to the cache can happen asynchronously in the next tick.

**Comment by adityapatadia** [comment]
Okay. I will make new PR with smaller improvements and I will remove this behavior change from them. I am keeping this PR open but I will close once new PRs are ready.

**Pull request closed without merging**
